# -*- coding: utf-8 -*-
"""Proyecto_Bot_Prueba

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fnAGfBmjjn_dkFN-m5ikgvmp6NpF1E8E
"""

pip install python-telegram-bot

from VueloairFly import Vueloa
from telegram.ext import (Updater, CommandHandler, MessageHandler, Filters, CallbackQueryHandler, ConversationHandler)

F1 = Vueloa("TAME", "GUAYAQUIL", "CUENCA", "90 minutos",70, "f1", "f2", "0", "/GYECUE")
F2 = Vueloa("AVIANCA", "GUAYAQUIL", "SANTA ROSA", "40 minutos",50, "f1", "f2", "0", "/GYEETR")
F3 = Vueloa("AIR CUENCA", "GUAYAQUIL", "QUITO", "90 minutos", 80, "f1", "f2", "0", "/GYEUIO")
F4 = Vueloa("AVIANCA", "GUAYAQUIL", "GALAPAGOS", "104 minutos",200, "f1", "f2", "0", "/GYEGPS")  # ---
F5 = Vueloa("AVIANCA", "GUAYAQUIL", "SALINAS", "50 minutos",60, "f1", "f2", "0", "/GYESNC")  #
F6 = Vueloa("LATAM", "QUITO", "MEXICO", "350 minutos", 1000, "f1", "f2", "0", "/UIOMEX")  #
F7 = Vueloa("AVIANCA", "GUAYAQUIL", "CÓRDOVA", "360 minutos", 1200, "f1", "f2", "0", "/GYECOR")  #
F8 = Vueloa("LAN ECUADOR", "GUAYAQUIL", "BRASIL", "250 minutos", 800, "f1", "f2", "0", "/GYEBR")  #
F9 = Vueloa("AVIANCA", "GUAYAQUIL", "MEXICO", "350 minutos", 1000, "f1", "f2", "0", "/GYEMX")  #
F10 = Vueloa("TAME", "QUITO", "COLOMBIA", "120 minutos", 200, "f1", "f2", "0", "/UIOCO")  #
F11 = Vueloa("AVIANCA", "QUITO", "MEXICO", "350 minutos", 1000, "f1", "f2", "0", "/UIOMX")
F12 = Vueloa("AVIANCA", "QUITO", "ESTADOS UNIDOS", "190 minutos,", 900, "f1", "f2", "0", "/UIOMIA")
F13 = Vueloa("AVIANCA", "SANTA ROSA", "ESTADOS UNIDOS", "200 minutos,", 900, "f1", "f2", "0", "/ETRNYC")
F14 = Vueloa("AIR ESPAÑA", "QUITO", "MADRID", "350 minutos,", 800, "f1", "f2", "0", "/UIOMAD")
F15 = Vueloa("LATAM", "CUENCA", "BRASIL", "250 minutos", 1300, "f1", "f2", "0", "/CUEBR")
F16 = Vueloa("TAME", "CUENCA", "BOLIVIA ", "300 minutos", 500, "f1", "f2", "0", "/CUELAP")
F17 = Vueloa("AERO MEXICO", "CUENCA", "MEXICO", "350 minutos", 1300, "f1", "f2", "0", "/CUEMX")
F18 = Vueloa("AVIANCA", "CUENCA", "CUBA", "460 minutos", 1200, "f1", "f2", "0", "/CUEHAV")
F19 = Vueloa("AIR CUENCA", "CUENCA", "QUITO", "45 minutos",80, "f1", "f2", "0", "/CUEUIO")  #
F20 = Vueloa("AMERICAN AIRLINES", "GUAYAQUIL", "TEXAS", "300 minutos", 1333, "f1", "f2", "0", "/GYEDFW")
F21 = Vueloa("AVIANCA", "QUITO", "RUSIA", "555 minutos", 1400, "f1", "f2", "0", "/UIOSVO")
F22 = Vueloa("TAME", "QUITO", "PARAGUAY", "200 minutos", 500, "f1", "f2", "0", "/UIOASU")
F23 = Vueloa("IBERIA", "GALAPAGOS", "CHILE", "290 minutos", 600, "f1", "f2", "0", "/GPSSCL")
F24 = Vueloa("IBERIA", "SANTA ROSA", "PANAMA", "340 minutos", 1000, "f1", "f2", "0", "/ETRPTY")  #
F25 = Vueloa("TAME", "SALINAS", "GUAYAQUIL", "40 minutos", 90, "f1", "f2", "0", "/SNCGYE")
F26 = Vueloa("TAME", "SALINAS", "CUENCA", "80 minutos", 99, "f1", "f2", "0", "/SNCCUE")
F27 = Vueloa("AIR CUENCA", "CUENCA", "SANTA ROSA", "85 minutos", 89, "f1", "f2", "0", "/CUEETR")
F28 = Vueloa("AVIANCA", "GALAPAGOS", "BOLIVIA", "200 minutos", 300, "f1", "f2", "0", "/GPSLAP")
F29 = Vueloa("AVIANCA", "GUAYAQUIL", "FRANCIA", "390 minutos", 890, "f1", "f2", "0", "/GYEMRS")
F30 = Vueloa("AVIANCA", "QUITO", "PORTUGAL", "89 minutos", 800, "f1", "f2", "0", "/UIOLIS")
F31 = Vueloa("TURKUISH AIRLINES", "GUAYAQUIL", "CHINA", "900 minutos", 2400, "f1", "f2", "0", "/GYECN")
F32 = Vueloa("AVIANCA", "CUENCA", "CHINA", "945 minutos", 2400, "f1", "f2", "0", "/CUECN")
F33 = Vueloa("AVIANCA", "SANTA ROSA", "COLOMBIA", "80 minutos", 580, "f1", "f2", "0", "/ETRBAQ")
F34 = Vueloa("TAME", "SANTA ROSA", "MANTA", "50 minutos", 70, "f1", "f2", "0", "/ETRMEC")
F35 = Vueloa("LATAM", "GUAYAQUIL", "JAPON", "800 minutos", 1800, "f1", "f2", "0", "/GYEJP")
F36 = Vueloa("AMERICAN AIRLINES", "QUITO", "URUGUAY", "200 minutos", 700, "f1", "f2", "0", "/OUIMVD")
F37 = Vueloa("IBERIA", "CUENCA", "ESPAÑA", "230 minutos", 700, "f1", "f2", "0", "/CUEALC")
F38 = Vueloa("LATAM", "SANTA ROSA", "ARGENTINA", "190 minutos", 400, "f1", "f2", "0", "/ETRBHI")
F39 = Vueloa("TAME", "GUAYAQUIL", "IRLANDA ", "245 minutos", 850, "f1", "f2", "0", "/GYEDUB")
F40 = Vueloa("AVIANCA", "GALAPAGOS", "NORUEGA", "500 minutos", 2000, "f1", "f2", "0", "/GPSOSL")


TOKEN = "1300820745:AAHoSFednH80CzWE1jcf9hAnspiSHXiUsHQ"


def start(update, context):

    update.message.reply_text("BIENVENIDO A AIRFLYWORLD\n")
    update.message.reply_text("-Para mostrar los viajes disponibles pulse --> \t/Allfly" + "\n-Para la busqueda de viajes pulse--> \t/Busqueda"
                              + "\n-Para comprar viajes sin retorno por favor pulse --> \t/Ida" + "\n-Para Comprar viajes con retorno por favor pulse-->\t/IdayVuelta"
                              +"\n \n Integrantes:  \n Sergio Campoverde \n Milena Cruz \n Ismael Salazar Tinoco \n Ana Villamar \n")