# -*- coding: utf-8 -*-
"""Proyecto_Bot

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LsfmYJlWS1_hcZyb0DlQOM2q2Th84i_p
"""

pip install python-telegram-bot

from VueloairFly import Vueloa
from telegram.ext import (Updater, CommandHandler, MessageHandler, Filters, CallbackQueryHandler, ConversationHandler)

F1 = Vueloa("TAME", "GUAYAQUIL", "CUENCA", "90 minutos",70, "f1", "f2", "0", "/GYECUE")
F2 = Vueloa("AVIANCA", "GUAYAQUIL", "SANTA ROSA", "40 minutos",50, "f1", "f2", "0", "/GYEETR")
F3 = Vueloa("AIR CUENCA", "GUAYAQUIL", "QUITO", "90 minutos", 80, "f1", "f2", "0", "/GYEUIO")
F4 = Vueloa("AVIANCA", "GUAYAQUIL", "GALAPAGOS", "104 minutos",200, "f1", "f2", "0", "/GYEGPS")  # ---
F5 = Vueloa("AVIANCA", "GUAYAQUIL", "SALINAS", "50 minutos",60, "f1", "f2", "0", "/GYESNC")  #
F6 = Vueloa("LATAM", "QUITO", "MEXICO", "350 minutos", 1000, "f1", "f2", "0", "/UIOMEX")  #
F7 = Vueloa("AVIANCA", "GUAYAQUIL", "CÓRDOVA", "360 minutos", 1200, "f1", "f2", "0", "/GYECOR")  #
F8 = Vueloa("LAN ECUADOR", "GUAYAQUIL", "BRASIL", "250 minutos", 800, "f1", "f2", "0", "/GYEBR")  #
F9 = Vueloa("AVIANCA", "GUAYAQUIL", "MEXICO", "350 minutos", 1000, "f1", "f2", "0", "/GYEMX")  #
F10 = Vueloa("TAME", "QUITO", "COLOMBIA", "120 minutos", 200, "f1", "f2", "0", "/UIOCO")  #
F11 = Vueloa("AVIANCA", "QUITO", "MEXICO", "350 minutos", 1000, "f1", "f2", "0", "/UIOMX")
F12 = Vueloa("AVIANCA", "QUITO", "ESTADOS UNIDOS", "190 minutos,", 900, "f1", "f2", "0", "/UIOMIA")
F13 = Vueloa("AVIANCA", "SANTA ROSA", "ESTADOS UNIDOS", "200 minutos,", 900, "f1", "f2", "0", "/ETRNYC")
F14 = Vueloa("AIR ESPAÑA", "QUITO", "MADRID", "350 minutos,", 800, "f1", "f2", "0", "/UIOMAD")
F15 = Vueloa("LATAM", "CUENCA", "BRASIL", "250 minutos", 1300, "f1", "f2", "0", "/CUEBR")
F16 = Vueloa("TAME", "CUENCA", "BOLIVIA ", "300 minutos", 500, "f1", "f2", "0", "/CUELAP")
F17 = Vueloa("AERO MEXICO", "CUENCA", "MEXICO", "350 minutos", 1300, "f1", "f2", "0", "/CUEMX")
F18 = Vueloa("AVIANCA", "CUENCA", "CUBA", "460 minutos", 1200, "f1", "f2", "0", "/CUEHAV")
F19 = Vueloa("AIR CUENCA", "CUENCA", "QUITO", "45 minutos",80, "f1", "f2", "0", "/CUEUIO")  #
F20 = Vueloa("AMERICAN AIRLINES", "GUAYAQUIL", "TEXAS", "300 minutos", 1333, "f1", "f2", "0", "/GYEDFW")
F21 = Vueloa("AVIANCA", "QUITO", "RUSIA", "555 minutos", 1400, "f1", "f2", "0", "/UIOSVO")
F22 = Vueloa("TAME", "QUITO", "PARAGUAY", "200 minutos", 500, "f1", "f2", "0", "/UIOASU")
F23 = Vueloa("IBERIA", "GALAPAGOS", "CHILE", "290 minutos", 600, "f1", "f2", "0", "/GPSSCL")
F24 = Vueloa("IBERIA", "SANTA ROSA", "PANAMA", "340 minutos", 1000, "f1", "f2", "0", "/ETRPTY")  #
F25 = Vueloa("TAME", "SALINAS", "GUAYAQUIL", "40 minutos", 90, "f1", "f2", "0", "/SNCGYE")
F26 = Vueloa("TAME", "SALINAS", "CUENCA", "80 minutos", 99, "f1", "f2", "0", "/SNCCUE")
F27 = Vueloa("AIR CUENCA", "CUENCA", "SANTA ROSA", "85 minutos", 89, "f1", "f2", "0", "/CUEETR")
F28 = Vueloa("AVIANCA", "GALAPAGOS", "BOLIVIA", "200 minutos", 300, "f1", "f2", "0", "/GPSLAP")
F29 = Vueloa("AVIANCA", "GUAYAQUIL", "FRANCIA", "390 minutos", 890, "f1", "f2", "0", "/GYEMRS")
F30 = Vueloa("AVIANCA", "QUITO", "PORTUGAL", "89 minutos", 800, "f1", "f2", "0", "/UIOLIS")
F31 = Vueloa("TURKUISH AIRLINES", "GUAYAQUIL", "CHINA", "900 minutos", 2400, "f1", "f2", "0", "/GYECN")
F32 = Vueloa("AVIANCA", "CUENCA", "CHINA", "945 minutos", 2400, "f1", "f2", "0", "/CUECN")
F33 = Vueloa("AVIANCA", "SANTA ROSA", "COLOMBIA", "80 minutos", 580, "f1", "f2", "0", "/ETRBAQ")
F34 = Vueloa("TAME", "SANTA ROSA", "MANTA", "50 minutos", 70, "f1", "f2", "0", "/ETRMEC")
F35 = Vueloa("LATAM", "GUAYAQUIL", "JAPON", "800 minutos", 1800, "f1", "f2", "0", "/GYEJP")
F36 = Vueloa("AMERICAN AIRLINES", "QUITO", "URUGUAY", "200 minutos", 700, "f1", "f2", "0", "/OUIMVD")
F37 = Vueloa("IBERIA", "CUENCA", "ESPAÑA", "230 minutos", 700, "f1", "f2", "0", "/CUEALC")
F38 = Vueloa("LATAM", "SANTA ROSA", "ARGENTINA", "190 minutos", 400, "f1", "f2", "0", "/ETRBHI")
F39 = Vueloa("TAME", "GUAYAQUIL", "IRLANDA ", "245 minutos", 850, "f1", "f2", "0", "/GYEDUB")
F40 = Vueloa("AVIANCA", "GALAPAGOS", "NORUEGA", "500 minutos", 2000, "f1", "f2", "0", "/GPSOSL")

NumClient = ""
enEspera = 0

bv = False
WRetorno = False
dest = []
objFly = Vueloa
cedula = ""
totalP = 0
num = 0

dest.append(F1)
dest.append(F2)
dest.append(F3)
dest.append(F4)
dest.append(F5)
dest.append(F6)
dest.append(F7)
dest.append(F8)
dest.append(F9)
dest.append(F10)
dest.append(F11)
dest.append(F12)
dest.append(F13)
dest.append(F14)
dest.append(F15)
dest.append(F16)
dest.append(F17)
dest.append(F18)
dest.append(F19)
dest.append(F20)
dest.append(F21)
dest.append(F22)
dest.append(F23)
dest.append(F24)
dest.append(F25)
dest.append(F26)
dest.append(F27)
dest.append(F28)
dest.append(F29)
dest.append(F30)
dest.append(F31)
dest.append(F32)
dest.append(F33)
dest.append(F34)
dest.append(F35)
dest.append(F36)
dest.append(F37)
dest.append(F38)
dest.append(F39)
dest.append(F40)



TOKEN = "1300820745:AAHoSFednH80CzWE1jcf9hAnspiSHXiUsHQ"


def start(update, context):

    update.message.reply_text("BIENVENIDO A AIRFLYWORLD\n")
    update.message.reply_text("-Para mostrar los viajes disponibles pulse --> \t/Allfly" + "\n-Para la busqueda de viajes pulse--> \t/Busqueda"
                              + "\n-Para comprar viajes sin retorno por favor pulse --> \t/Ida" + "\n-Para Comprar viajes con retorno por favor pulse-->\t/IdayVuelta"
                              +"\n \n Integrantes:  \n Sergio Campoverde \n Milena Cruz \n Ismael Salazar Tinoco \n Ana Villamar \n")


def Ida(update, context):
    global WRetorno
    WRetorno = False
    update.message.reply_text("Para elegir un vuelo precione el comando que se presenta acontinuación--> ejemplo / GYEUIO")
    for b in dest:
        update.message.reply_text(
            "Origen :" + b.origen + "\nDestino: " + b.destino + "\nAerolínea:" + b.aerolinea + "\nPrecio:" + str(
                b.precio) + "$" + "\nDuracion: " + b.duracion + "\n" + b.cod)



def GYECUE(update, context):
    global objFly, WRetorno
    objFly = Vueloa(dest[0].aerolinea, dest[0].origen, dest[0].destino, dest[0].duracion, dest[0].precio, dest[0].fechIda, dest[0].fechVuelta,
                    dest[0].npersona, dest[0].cod)
    update.message.reply_text(
        "Origen :" + objFly.origen + "\nDestino :" + objFly.destino + "\nAerolinea :" + objFly.aerolinea + "\nPrecio:" + str(
            objFly.precio) + "$" + "\nDuracion: " + objFly.duracion)
    update.message.reply_text(
        "A continuacion ingrese la fecha de ida mediante --> /fechaida (000-00-00)\n Ejemplo /fechaida 2020-10-25 ")  # AAAA-MM-DD
    if WRetorno == True:
        update.message.reply_text(
            "A continuacion ingrese la fecha de retorno mediante --> /fechavuelta (000-00-00)\n Ejemplo /fechavuelta 2020-10-09 ")  # AAAA-MM-DD


def GYEETR(update, context):
    global objFly, WRetorno
    objFly = Vueloa(dest[1].aerolinea, dest[1].origen, dest[1].destino, dest[1].duracion, dest[1].precio, dest[1].fechIda, dest[1].fechVuelta,
                    dest[1].npersona, dest[1].cod)
    update.message.reply_text(
        "Origen :" + objFly.origen + "\nDestino :" + objFly.destino + "\nAerolinea :" + objFly.aerolinea + "\nPrecio:" + str(
            objFly.precio) + "$" + "\nDuracion: " + objFly.duracion)
    update.message.reply_text(
        "A continuacion escriba /fechaida (000-00-00)\n Ejemplo /fechaida 2020-10-09 ")  # año -mes-dia
    if WRetorno == True:
        update.message.reply_text(
            "A continuacion escriba /fechavuelta (000-00-00)\n Ejemplo /fechavuelta 2020-10-09 ")  # año -mes-dia


def GYEUIO(update, context):
    global objFly, WRetorno
    objFly = Vueloa(dest[2].aerolinea, dest[2].origen, dest[2].destino, dest[2].duracion, dest[2].precio, dest[2].fechIda, dest[2].fechVuelta,
                    dest[2].npersona, dest[2].cod)
    update.message.reply_text(
        "Origen :" + objFly.origen + "\nDestino :" + objFly.destino + "\nAerolinea :" + objFly.aerolinea + "\nPrecio:" + str(
            objFly.precio) + "$" + "\nDuracion:" + objFly.duracion)
    update.message.reply_text(
        "A continuacion escriba /fechaida (000-00-00)\n Ejemplo /fechaida 2020-10-09 ")  # año -mes-dia
    if WRetorno == True:
        update.message.reply_text(
            "A continuacion escriba /fechavuelta (000-00-00)\n Ejemplo /fechavuelta 2020-10-09 ")  # año -mes-dia


def GYEGPS(update, context):
    global objFly, WRetorno
    objFly = Vueloa(dest[3].aerolinea, dest[3].origen, dest[3].destino, dest[3].duracion, dest[3].precio, dest[3].fechIda, dest[3].fechVuelta,
                    dest[3].npersona, dest[3].cod)
    update.message.reply_text(
        "Origen :" + objFly.origen + "\nDestino :" + objFly.destino + "\nAerolinea :" + objFly.aerolinea + "\nPrecio:" + str(
            objFly.precio) + "$" + "\nDuracion: " + objFly.duracion)
    update.message.reply_text(
        "A continuacion escriba /fechaida (000-00-00)\n Ejemplo /fechaida 2020-10-09 ")  # año -mes-dia
    if WRetorno == True:
        update.message.reply_text(
            "A continuacion escriba /fechavuelta (000-00-00)\n Ejemplo /fechavuelta 2020-10-09 ")  # año -mes-dia


def GYESNC(update, context):
    global objFly, WRetorno
    objFly = Vueloa(dest[4].aerolinea, dest[4].origen, dest[4].destino, dest[4].duracion, dest[4].precio, dest[4].fechIda, dest[4].fechVuelta,
                    dest[4].npersona, dest[4].cod)
    update.message.reply_text(
        "Origen :" + objFly.origen + "\nDestino :" + objFly.destino + "\nAerolinea :" + objFly.aerolinea + "\nPrecio:" + str(
            objFly.precio) + "$" + "\nDuracion: " + objFly.duracion)
    update.message.reply_text(
        "A continuacion escriba /fechaida (000-00-00)\n Ejemplo /fechaida 2020-10-09 ")  # año -mes-dia
    if WRetorno == True:
        update.message.reply_text(
            "A continuacion escriba /fechavuelta (000-00-00)\n Ejemplo /fechavuelta 2020-10-09 ")  # año -mes-dia


def UIOMEX(update, context):
    global objFly, WRetorno
    objFly = Vueloa(dest[5].aerolinea, dest[5].origen, dest[5].destino, dest[5].duracion, dest[5].precio, dest[5].fechIda, dest[5].fechVuelta,
                    dest[5].npersona, dest[5].cod)
    update.message.reply_text(
        "Origen :" + objFly.origen + "\nDestino :" + objFly.destino + "\nAerolinea :" + objFly.aerolinea + "\nPrecio:" + str(
            objFly.precio) + "$" + "\nDuracion: " + objFly.duracion)
    update.message.reply_text(
        "A continuacion escriba /fechaida (000-00-00)\n Ejemplo /fechaida 2020-10-09 ")  # año -mes-dia
    if WRetorno == True:
        update.message.reply_text(
            "A continuacion escriba /fechavuelta (000-00-00)\n Ejemplo /fechavuelta 2020-10-09 ")  # año -mes-dia


def GYECOR(update, context):
    global objFly, WRetorno
    objFly = Vueloa(dest[6].aerolinea, dest[6].origen, dest[6].destino, dest[6].duracion, dest[6].precio, dest[6].fechIda, dest[6].fechVuelta,
                    dest[6].npersona, dest[6].cod)
    update.message.reply_text(
        "Origen :" + objFly.origen + "\nDestino :" + objFly.destino + "\nAerolinea :" + objFly.aerolinea + "\nPrecio:" + str(
            objFly.precio) + "$" + "\nDuracion: " + objFly.duracion)
    update.message.reply_text(
        "A continuacion escriba /fechaida (000-00-00)\n Ejemplo /fechaida 2020-10-09 ")  # año -mes-dia
    if WRetorno == True:
        update.message.reply_text(
            "A continuacion escriba /fechavuelta (000-00-00)\n Ejemplo /fechavuelta 2020-10-09 ")  # año -mes-dia


def GYEBR(update, context):
    global objFly, WRetorno
    objFly = Vueloa(dest[7].aerolinea, dest[7].origen, dest[7].destino, dest[7].duracion, dest[7].precio, dest[7].fechIda, dest[7].fechVuelta,
                    dest[7].npersona, dest[7].cod)
    update.message.reply_text(
        "Origen :" + objFly.origen + "\nDestino :" + objFly.destino + "\nAerolinea :" + objFly.aerolinea + "\nPrecio:" + str(
            objFly.precio) + "$" + "\nDuracion: " + objFly.duracion)
    update.message.reply_text(
        "A continuacion escriba /fechaida (000-00-00)\n Ejemplo /fechaida 2020-10-09 ")  # año -mes-dia
    if WRetorno == True:
        update.message.reply_text(
            "A continuacion escriba /fechavuelta (000-00-00)\n Ejemplo /fechavuelta 2020-10-09 ")  # año -mes-dia


def GYEMX(update, context):
    global objFly, WRetorno
    objFly = Vueloa(dest[8].aerolinea, dest[8].origen, dest[8].destino, dest[8].duracion, dest[8].precio, dest[8].fechIda, dest[8].fechVuelta,
                    dest[8].npersona, dest[8].cod)
    update.message.reply_text(
        "Origen :" + objFly.origen + "\nDestino :" + objFly.destino + "\nAerolinea :" + objFly.aerolinea + "\nPrecio:" + str(
            objFly.precio) + "$" + "\nDuracion: " + objFly.duracion)
    update.message.reply_text(
        "A continuacion escriba /fechaida (000-00-00)\n Ejemplo /fechaida 2020-10-09 ")  # año -mes-dia
    if WRetorno == True:
        update.message.reply_text(
            "A continuacion escriba /fechavuelta (000-00-00)\n Ejemplo /fechavuelta 2020-10-09 ")  # año -mes-dia


def UIOCO(update, context):
    global objFly, WRetorno
    objFly = Vueloa(dest[9].aerolinea, dest[9].origen, dest[9].destino, dest[9].duracion, dest[9].precio, dest[9].fechIda, dest[9].fechVuelta,
                    dest[9].npersona, dest[9].cod)
    update.message.reply_text(
        "Origen :" + objFly.origen + "\nDestino :" + objFly.destino + "\nAerolinea :" + objFly.aerolinea + "\nPrecio:" + str(
            objFly.precio) + "$" + "\nDuracion: " + objFly.duracion)
    update.message.reply_text(
        "A continuacion escriba /fechaida (000-00-00)\n Ejemplo /fechaida 2020-10-09 ")  # año -mes-dia
    if WRetorno == True:
        update.message.reply_text(
            "A continuacion escriba /fechavuelta (000-00-00)\n Ejemplo /fechavuelta 2020-10-09 ")  # año -mes-dia


def UIOMX(update, context):
    global objFly, WRetorno
    objFly = Vueloa(dest[10].aerolinea, dest[10].origen, dest[10].destino, dest[10].duracion, dest[10].precio, dest[10].fechIda,
                    dest[10].fechVuelta, dest[10].npersona, dest[10].cod)
    update.message.reply_text(
        "Origen :" + objFly.origen + "\nDestino :" + objFly.destino + "\nAerolinea :" + objFly.aerolinea + "\nPrecio:" + str(
            objFly.precio) + "$" + "\nDuracion: " + objFly.duracion)
    update.message.reply_text(
        "A continuacion escriba /fechaida (000-00-00)\n Ejemplo /fechaida 2020-10-09 ")  # año -mes-dia
    if WRetorno == True:
        update.message.reply_text(
            "A continuacion escriba /fechavuelta (000-00-00)\n Ejemplo /fechavuelta 2020-10-09 ")  # año -mes-dia


def UIOMIA(update, context):
    global objFly, WRetorno
    objFly = Vueloa(dest[11].aerolinea, dest[11].origen, dest[11].destino, dest[11].duracion, dest[11].precio, dest[11].fechIda,
                    dest[11].fechVuelta, dest[11].npersona, dest[11].cod)
    update.message.reply_text(
        "Origen :" + objFly.origen + "\nDestino :" + objFly.destino + "\nAerolinea :" + objFly.aerolinea + "\nPrecio:" + str(
            objFly.precio) + "$" + "\nDuracion: " + objFly.duracion)
    update.message.reply_text(
        "A continuacion escriba /fechaida (000-00-00)\n Ejemplo /fechaida 2020-10-09 ")  # año -mes-dia
    if WRetorno == True:
        update.message.reply_text(
            "A continuacion escriba /fechavuelta (000-00-00)\n Ejemplo /fechavuelta 2020-10-09 ")  # año -mes-dia


def ETRNYC(update, context):
    global objFly, WRetorno
    objFly = Vueloa(dest[12].aerolinea, dest[12].origen, dest[12].destino, dest[12].duracion, dest[12].precio, dest[12].fechIda,
                    dest[12].fechVuelta, dest[12].npersona, dest[12].cod)
    update.message.reply_text(
        "Origen :" + objFly.origen + "\nDestino :" + objFly.destino + "\nAerolinea :" + objFly.aerolinea + "\nPrecio:" + str(
            objFly.precio) + "$" + "\nDuracion: " + objFly.duracion)
    update.message.reply_text(
        "A continuacion escriba /fechaida (000-00-00)\n Ejemplo /fechaida 2020-10-09 ")  # año -mes-dia
    if WRetorno == True:
        update.message.reply_text(
            "A continuacion escriba /fechavuelta (000-00-00)\n Ejemplo /fechavuelta 2020-10-09 ")  # año -mes-dia


def UIOMAD(update, context):
    global objFly, WRetorno
    objFly = Vueloa(dest[13].aerolinea, dest[13].origen, dest[13].destino, dest[13].duracion, dest[13].precio, dest[13].fechIda,
                    dest[13].fechVuelta, dest[13].npersona, dest[13].cod)
    update.message.reply_text(
        "Origen :" + objFly.origen + "\nDestino :" + objFly.destino + "\nAerolinea :" + objFly.aerolinea + "\nPrecio:" + str(
            objFly.precio) + "$" + "\nDuracion: " + objFly.duracion)
    update.message.reply_text(
        "A continuacion escriba /fechaida (000-00-00)\n Ejemplo /fechaida 2020-10-09 ")  # año -mes-dia
    if WRetorno == True:
        update.message.reply_text(
            "A continuacion escriba /fechavuelta (000-00-00)\n Ejemplo /fechavuelta 2020-10-09 ")  # año -mes-dia


def CUEBR(update, context):
    global objFly, WRetorno
    objFly = Vueloa(dest[14].aerolinea, dest[14].origen, dest[14].destino, dest[14].duracion, dest[14].precio, dest[14].fechIda,
                    dest[14].fechVuelta, dest[14].npersona, dest[14].cod)
    update.message.reply_text(
        "Origen :" + objFly.origen + "\nDestino :" + objFly.destino + "\nAerolinea :" + objFly.aerolinea + "\nPrecio:" + str(
            objFly.precio) + "$" + "\nDuracion: " + objFly.duracion)
    update.message.reply_text(
        "A continuacion escriba /fechaida (000-00-00)\n Ejemplo /fechaida 2020-10-09 ")  # año -mes-dia
    if WRetorno == True:
        update.message.reply_text(
            "A continuacion escriba /fechavuelta (000-00-00)\n Ejemplo /fechavuelta 2020-10-09 ")  # año -mes-dia


def CUELAP(update, context):
    global objFly, WRetorno
    objFly = Vueloa(dest[15].aerolinea, dest[15].origen, dest[15].destino, dest[15].duracion, dest[15].precio, dest[15].fechIda,
                    dest[15].fechVuelta, dest[15].npersona, dest[15].cod)
    update.message.reply_text(
        "Origen :" + objFly.origen + "\nDestino :" + objFly.destino + "\nAerolinea :" + objFly.aerolinea + "\nPrecio:" + str(
            objFly.precio) + "$" + "\nDuracion: " + objFly.duracion)
    update.message.reply_text(
        "A continuacion escriba /fechaida (000-00-00)\n Ejemplo /fechaida 2020-10-09 ")  # año -mes-dia
    if WRetorno == True:
        update.message.reply_text(
            "A continuacion escriba /fechavuelta (000-00-00)\n Ejemplo /fechavuelta 2020-10-09 ")  # año -mes-dia


def CUEMX(update, context):
    global objFly, WRetorno
    objFly =Vueloa(dest[16].aerolinea, dest[16].origen, dest[16].destino, dest[16].duracion, dest[16].precio, dest[16].fechIda,
                   dest[16].fechVuelta, dest[16].npersona, dest[16].cod)
    update.message.reply_text(
        "Origen :" + objFly.origen + "\nDestino :" + objFly.destino + "\nAerolinea :" + objFly.aerolinea + "\nPrecio:" + str(
            objFly.precio) + "$" + "\nDuracion: " + objFly.duracion)
    update.message.reply_text(
        "A continuacion escriba /fechaida (000-00-00)\n Ejemplo /fechaida 2020-10-09 ")  # año -mes-dia
    if WRetorno == True:
        update.message.reply_text(
            "A continuacion escriba /fechavuelta (000-00-00)\n Ejemplo /fechavuelta 2020-10-09 ")  # año -mes-dia


def CUEHAV(update, context):
    global objFly, WRetorno
    objFly = Vueloa(dest[17].aerolinea, dest[17].origen, dest[17].destino, dest[17].duracion, dest[17].precio, dest[17].fechIda,
                    dest[17].fechVuelta, dest[17].npersona, dest[17].cod)
    update.message.reply_text(
        "Origen :" + objFly.origen + "\nDestino :" + objFly.destino + "\nAerolinea :" + objFly.aerolinea + "\nPrecio:" + str(
            objFly.precio) + "$" + "\nDuracion: " + objFly.duracion)
    update.message.reply_text(
        "A continuacion escriba /fechaida (000-00-00)\n Ejemplo /fechaida 2020-10-09 ")  # año -mes-dia
    if WRetorno == True:
        update.message.reply_text(
            "A continuacion escriba /fechavuelta (000-00-00)\n Ejemplo /fechavuelta 2020-10-09 ")  # año -mes-dia


def CUEUIO(update, context):
    global objFly, WRetorno
    objFly = Vueloa(dest[18].aerolinea, dest[18].origen, dest[18].destino, dest[18].duracion, dest[18].precio, dest[18].fechIda,
                    dest[18].fechVuelta, dest[18].npersona, dest[18].cod)
    update.message.reply_text(
        "Origen :" + objFly.origen + "\nDestino :" + objFly.destino + "\nAerolinea :" + objFly.aerolinea + "\nPrecio:" + str(
            objFly.precio) + "$" + "\nDuracion: " + objFly.duracion)
    update.message.reply_text(
        "A continuacion escriba /fechaida (000-00-00)\n Ejemplo /fechaida 2020-10-09 ")  # año -mes-dia
    if WRetorno == True:
        update.message.reply_text(
            "A continuacion escriba /fechavuelta (000-00-00)\n Ejemplo /fechavuelta 2020-10-09 ")  # año -mes-dia


def GYEDFW(update, context):
    global objFly, WRetorno
    objFly = Vueloa(dest[19].aerolinea, dest[19].origen, dest[19].destino, dest[19].duracion, dest[19].precio, dest[19].fechIda,
                    dest[19].fechVuelta, dest[19].npersona, dest[19].cod)
    update.message.reply_text(
        "Origen :" + objFly.origen + "\nDestino :" + objFly.destino + "\nAerolinea :" + objFly.aerolinea + "\nPrecio:" + str(
            objFly.precio) + "$" + "\nDuracion: " + objFly.duracion)
    update.message.reply_text(
        "A continuacion escriba /fechaida (000-00-00)\n Ejemplo /fechaida 2020-10-09 ")  # año -mes-dia
    if WRetorno == True:
        update.message.reply_text(
            "A continuacion escriba /fechavuelta (000-00-00)\n Ejemplo /fechavuelta 2020-10-09 ")  # año -mes-dia


def UIOSVO(update, context):
    global objFly, WRetorno
    objFly = Vueloa(dest[20].aerolinea, dest[20].origen, dest[20].destino, dest[20].duracion, dest[20].precio, dest[20].fechIda,
                    dest[20].fechVuelta, dest[20].npersona, dest[20].cod)
    update.message.reply_text(
        "Origen :" + objFly.origen + "\nDestino :" + objFly.destino + "\nAerolinea :" + objFly.aerolinea + "\nPrecio:" + str(
            objFly.precio) + "$" + "\nDuracion: " + objFly.duracion)
    update.message.reply_text(
        "A continuacion escriba /fechaida (000-00-00)\n Ejemplo /fechaida 2020-10-09 ")  # año -mes-dia
    if WRetorno == True:
        update.message.reply_text(
            "A continuacion escriba /fechavuelta (000-00-00)\n Ejemplo /fechavuelta 2020-10-09 ")  # año -mes-dia


def UIOASU(update, context):
    global objFly, WRetorno
    objFly = Vueloa(dest[21].aerolinea, dest[21].origen, dest[21].destino, dest[21].duracion, dest[21].precio, dest[21].fechIda,
                    dest[21].fechVuelta, dest[21].npersona, dest[21].cod)
    update.message.reply_text(
        "Origen :" + objFly.origen + "\nDestino :" + objFly.destino + "\nAerolinea :" + objFly.aerolinea + "\nPrecio:" + str(
            objFly.precio) + "$" + "\nDuracion: " + objFly.duracion)
    update.message.reply_text(
        "A continuacion escriba /fechaida (000-00-00)\n Ejemplo /fechaida 2020-10-09 ")  # año -mes-dia
    if WRetorno == True:
        update.message.reply_text(
            "A continuacion escriba /fechavuelta (000-00-00)\n Ejemplo /fechavuelta 2020-10-09 ")  # año -mes-dia


def GPSSCL(update, context):
    global objFly, WRetorno
    objFly = Vueloa(dest[22].aerolinea, dest[22].origen, dest[22].destino, dest[22].duracion, dest[22].precio, dest[22].fechIda,
                    dest[22].fechVuelta, dest[22].npersona, dest[22].cod)
    update.message.reply_text(
        "Origen :" + objFly.origen + "\nDestino :" + objFly.destino + "\nAerolinea :" + objFly.aerolinea + "\nPrecio:" + str(
            objFly.precio) + "$" + "\nDuracion: " + objFly.duracion)
    update.message.reply_text(
        "A continuacion escriba /fechaida (000-00-00)\n Ejemplo /fechaida 2020-10-09 ")  # año -mes-dia
    if WRetorno == True:
        update.message.reply_text(
            "A continuacion escriba /fechavuelta (000-00-00)\n Ejemplo /fechavuelta 2020-10-09 ")  # año -mes-dia


def ETRPTY(update, context):
    global objFly, WRetorno
    objFly = Vueloa(dest[23].aerolinea, dest[23].origen, dest[23].destino, dest[23].duracion, dest[23].precio, dest[23].fechIda,
                    dest[23].fechVuelta, dest[23].npersona, dest[23].cod)
    update.message.reply_text(
        "Origen :" + objFly.origen + "\nDestino :" + objFly.destino + "\nAerolinea :" + objFly.aerolinea + "\nPrecio:" + str(
            objFly.precio) + "$" + "\nDuracion: " + objFly.duracion)
    update.message.reply_text(
        "A continuacion escriba /fechaida (000-00-00)\n Ejemplo /fechaida 2020-10-09 ")  # año -mes-dia
    if WRetorno == True:
        update.message.reply_text(
            "A continuacion escriba /fechavuelta (000-00-00)\n Ejemplo /fechavuelta 2020-10-09 ")  # año -mes-dia


def SNCGYE(update, context):
    global objFly, WRetorno
    objFly = Vueloa(dest[24].aerolinea, dest[24].origen, dest[24].destino, dest[24].duracion, dest[24].precio, dest[24].fechIda,
                    dest[24].fechVuelta, dest[24].npersona, dest[24].cod)
    update.message.reply_text(
        "Origen :" + objFly.origen + "\nDestino :" + objFly.destino + "\nAerolinea :" + objFly.aerolinea + "\nPrecio:" + str(
            objFly.precio) + "$" + "\nDuracion: " + objFly.duracion)
    update.message.reply_text(
        "A continuacion escriba /fechaida (000-00-00)\n Ejemplo /fechaida 2020-10-09 ")  # año -mes-dia
    if WRetorno == True:
        update.message.reply_text(
            "A continuacion escriba /fechavuelta (000-00-00)\n Ejemplo /fechavuelta 2020-10-09 ")  # año -mes-dia


def SNCCUE(update, context):
    global objFly, WRetorno
    objFly = Vueloa(dest[25].aerolinea, dest[25].origen, dest[25].destino, dest[25].duracion, dest[25].precio, dest[25].fechIda,
                    dest[25].fechVuelta, dest[25].npersona, dest[25].cod)
    update.message.reply_text(
        "Origen :" + objFly.origen + "\nDestino :" + objFly.destino + "\nAerolinea :" + objFly.aerolinea + "\nPrecio:" + str(
            objFly.precio) + "$" + "\nDuracion: " + objFly.duracion)
    update.message.reply_text(
        "A continuacion escriba /fechaida (000-00-00)\n Ejemplo /fechaida 2020-10-09 ")  # año -mes-dia
    if WRetorno == True:
        update.message.reply_text(
            "A continuacion escriba /fechavuelta (000-00-00)\n Ejemplo /fechavuelta 2020-10-09 ")  # año -mes-dia


def CUEETR(update, context):
    global objFly, WRetorno
    objFly = Vueloa(dest[26].aerolinea, dest[26].origen, dest[26].destino, dest[26].duracion, dest[26].precio, dest[26].fechIda,
                    dest[26].fechVuelta, dest[26].npersona, dest[26].cod)
    update.message.reply_text(
        "Origen :" + objFly.origen + "\nDestino :" + objFly.destino + "\nAerolinea :" + objFly.aerolinea + "\nPrecio:" + str(
            objFly.precio) + "$" + "\nDuracion: " + objFly.duracion)
    update.message.reply_text(
        "A continuacion escriba /fechaida (000-00-00)\n Ejemplo /fechaida 2020-10-09 ")  # año -mes-dia
    if WRetorno == True:
        update.message.reply_text(
            "A continuacion escriba /fechavuelta (000-00-00)\n Ejemplo /fechavuelta 2020-10-09 ")  # año -mes-dia


def GPSLAP(update, context):
    global objFly, WRetorno
    objFly = Vueloa(dest[27].aerolinea, dest[27].origen, dest[27].destino, dest[27].duracion, dest[27].precio, dest[27].fechIda,
                    dest[27].fechVuelta, dest[27].npersona, dest[27].cod)
    update.message.reply_text(
        "Origen :" + objFly.origen + "\nDestino :" + objFly.destino + "\nAerolinea :" + objFly.aerolinea + "\nPrecio:" + str(
            objFly.precio) + "$" + "\nDuracion: " + objFly.duracion)
    update.message.reply_text(
        "A continuacion escriba /fechaida (000-00-00)\n Ejemplo /fechaida 2020-10-09 ")  # año -mes-dia
    if WRetorno == True:
        update.message.reply_text(
            "A continuacion escriba /fechavuelta (000-00-00)\n Ejemplo /fechavuelta 2020-10-09 ")  # año -mes-dia


def GYEMRS(update, context):
    global objFly, WRetorno
    objFly = Vueloa(dest[28].aerolinea, dest[28].origen, dest[28].destino, dest[28].duracion, dest[28].precio, dest[28].fechIda,
                    dest[28].fechVuelta, dest[28].npersona, dest[28].cod)
    update.message.reply_text(
        "Origen :" + objFly.origen + "\nDestino: " + objFly.destino + "\nAerolinea :" + objFly.aerolinea + "\nPrecio:" + str(
            objFly.precio) + "$" + "\nDuracion: " + objFly.duracion)
    update.message.reply_text(
        "A continuacion escriba /fechaida (000-00-00)\n Ejemplo /fechaida 2020-10-09 ")  # año -mes-dia
    if WRetorno == True:
        update.message.reply_text(
            "A continuacion escriba /fechavuelta (000-00-00)\n Ejemplo /fechavuelta 2020-10-09 ")  # año -mes-dia


def UIOLIS(update, context):
    global objFly, WRetorno
    objFly = Vueloa(dest[29].aerolinea, dest[29].origen, dest[29].destino, dest[29].duracion, dest[29].precio, dest[29].fechIda,
                    dest[29].fechVuelta, dest[29].npersona, dest[29].cod)
    update.message.reply_text(
        "Origen :" + objFly.origen + "\nDestino: " + objFly.destino + "\nAerolinea :" + objFly.aerolinea + "\nPrecio:" + str(
            objFly.precio) + "$" + "\nDuracion: " + objFly.duracion)
    update.message.reply_text(
        "A continuacion escriba /fechaida (000-00-00)\n Ejemplo /fechaida 2020-10-09 ")  # año -mes-dia
    if WRetorno == True:
        update.message.reply_text(
            "A continuacion escriba /fechavuelta (000-00-00)\n Ejemplo /fechavuelta 2020-10-09 ")  # año -mes-dia


def GYECN(update, context):
    global objFly, WRetorno
    objFly = Vueloa(dest[30].aerolinea, dest[30].origen, dest[30].destino, dest[30].duracion, dest[30].precio, dest[30].fechIda,
                    dest[30].fechVuelta, dest[30].npersona, dest[30].cod)
    update.message.reply_text(
        "Origen :" + objFly.origen + "\nDestino: " + objFly.destino + "\nAerolinea :" + objFly.aerolinea + "\nPrecio:" + str(
            objFly.precio) + "$" + "\nDuracion: " + objFly.duracion)
    update.message.reply_text(
        "A continuacion escriba /fechaida (000-00-00)\n Ejemplo /fechaida 2020-10-09 ")  # año -mes-dia
    if WRetorno == True:
        update.message.reply_text(
            "A continuacion escriba /fechavuelta (000-00-00)\n Ejemplo /fechavuelta 2020-10-09 ")  # año -mes-dia


def CUECN(update, context):
    global objFly, WRetorno
    objFly = Vueloa(dest[31].aerolinea, dest[31].origen, dest[31].destino, dest[31].duracion, dest[31].precio, dest[31].fechIda,
                    dest[31].fechVuelta, dest[31].npersona, dest[31].cod)
    update.message.reply_text(
        "Origen :" + objFly.origen + "\nDestino: " + objFly.destino + "\nAerolinea :" + objFly.aerolinea + "\nPrecio:" + str(
            objFly.precio) + "$" + "\nDuracion: " + objFly.duracion)
    update.message.reply_text(
        "A continuacion escriba /fechaida (000-00-00)\n Ejemplo /fechaida 2020-10-09 ")  # año -mes-dia
    if WRetorno == True:
        update.message.reply_text(
            "A continuacion escriba /fechavuelta (000-00-00)\n Ejemplo /fechavuelta 2020-10-09 ")  # año -mes-dia


def ETRBAQ(update, context):
    global objFly, WRetorno
    objFly = Vueloa(dest[32].aerolinea, dest[32].origen, dest[32].destino, dest[32].duracion, dest[32].precio, dest[32].fechIda,
                    dest[32].fechVuelta, dest[32].npersona, dest[32].cod)
    update.message.reply_text(
        "Origen :" + objFly.origen + "\nDestino: " + objFly.destino + "\nAerolinea :" + objFly.aerolinea + "\nPrecio:" + str(
            objFly.precio) + "$" + "\nDuracion: " + objFly.duracion)
    update.message.reply_text(
        "A continuacion escriba /fechaida (000-00-00)\n Ejemplo /fechaida 2020-10-09 ")  # año -mes-dia
    if WRetorno == True:
        update.message.reply_text("A continuacion escriba /fechavuelta (000-00-00)\n Ejemplo /fechavuelta 2020-10-09 ")
        # año -mes-dia


def ETRMEC(update, context):
    global objFly, WRetorno
    objFly = Vueloa(dest[33].aerolinea, dest[33].origen, dest[33].destino, dest[33].duracion, dest[33].precio, dest[33].fechIda,
                    dest[33].fechVuelta, dest[33].npersona, dest[33].cod)
    update.message.reply_text(
        "Origen :" + objFly.origen + "\nDestino: " + objFly.destino + "\nAerolinea :" + objFly.aerolinea + "\nPrecio:" + str(
            objFly.precio) + "$" + "\nDuracion: " + objFly.duracion)
    update.message.reply_text(
        "A continuacion escriba /fechaida (000-00-00)\n Ejemplo /fechaida 2020-10-09 ")  # año -mes-dia
    if WRetorno == True:
        update.message.reply_text(
            "A continuacion escriba /fechavuelta (000-00-00)\n Ejemplo /fechavuelta 2020-10-09 ")  # año -mes-dia


def GYEJP(update, context):
    global objFly, WRetorno
    objFly = Vueloa(dest[34].aerolinea, dest[34].origen, dest[34].destino, dest[34].duracion, dest[34].precio, dest[34].fechIda,
                    dest[34].fechVuelta, dest[34].npersona, dest[34].cod)
    update.message.reply_text(
        "Origen :" + objFly.origen + "\nDestino: " + objFly.destino + "\nAerolinea :" + objFly.aerolinea + "\nPrecio:" + str(
            objFly.precio) + "$" + "\nDuracion: " + objFly.duracion)
    update.message.reply_text(
        "A continuacion escriba /fechaida (000-00-00)\n Ejemplo /fechaida 2020-10-09 ")  # año -mes-dia
    if WRetorno == True:
        update.message.reply_text(
            "A continuacion escriba /fechavuelta (000-00-00)\n Ejemplo /fechavuelta 2020-10-09 ")  # año -mes-dia


def OUIMVD(update, context):
    global objFly, WRetorno
    objFly = Vueloa(dest[35].aerolinea, dest[35].origen, dest[35].destino, dest[35].duracion, dest[35].precio, dest[35].fechIda,
                    dest[35].fechVuelta, dest[35].npersona, dest[35].cod)
    update.message.reply_text(
        "Origen :" + objFly.origen + "\nDestino: " + objFly.destino + "\nAerolinea :" + objFly.aerolinea + "\nPrecio:" + str(
            objFly.precio) + "$" + "\nDuracion: " + objFly.duracion)
    update.message.reply_text(
        "A continuacion escriba /fechaida (000-00-00)\n Ejemplo /fechaida 2020-10-09 ")  # año -mes-dia
    if WRetorno == True:
        update.message.reply_text(
            "A continuacion escriba /fechavuelta (000-00-00)\n Ejemplo /fechavuelta 2020-10-09 ")  # año -mes-dia


def CUEALC(update, context):
    global objFly, WRetorno
    objFly = Vueloa(dest[36].aerolinea, dest[36].origen, dest[36].destino, dest[36].duracion, dest[36].precio, dest[36].fechIda,
                    dest[36].fechVuelta, dest[36].npersona, dest[36].cod)
    update.message.reply_text(
        "Origen :" + objFly.origen + "\nDestino: " + objFly.destino + "\nAerolinea :" + objFly.aerolinea + "\nPrecio:" + str(
            objFly.precio) + "$" + "\nDuracion: " + objFly.duracion)
    update.message.reply_text(
        "A continuacion escriba /fechaida (000-00-00)\n Ejemplo /fechaida 2020-10-09 ")  # año -mes-dia
    if WRetorno == True:
        update.message.reply_text(
            "A continuacion escriba /fechavuelta (000-00-00)\n Ejemplo /fechavuelta 2020-10-09 ")  # año -mes-dia


def ETRBHI(update, context):
    global objFly, WRetorno
    objFly = Vueloa(dest[37].aerolinea, dest[37].origen, dest[37].destino, dest[37].duracion, dest[37].precio, dest[37].fechIda,
                    dest[37].fechVuelta, dest[37].npersona, dest[37].cod)
    update.message.reply_text(
        "Origen :" + objFly.origen + "\nDestino: " + objFly.destino + "\nAerolinea :" + objFly.aerolinea + "\nPrecio:" + str(
            objFly.precio) + "$" + "\nDuracion: " + objFly.duracion)
    update.message.reply_text(
        "A continuacion escriba /fechaida (000-00-00)\n Ejemplo /fechaida 2020-10-09 ")  # año -mes-dia
    if WRetorno == True:
        update.message.reply_text(
            "A continuacion escriba /fechavuelta (000-00-00)\n Ejemplo /fechavuelta 2020-10-09 ")  # año -mes-dia


def GYEDUB(update, context):
    global objFly, WRetorno
    objFly = Vueloa(dest[38].aerolinea, dest[38].origen, dest[38].destino, dest[38].duracion, dest[38].precio, dest[38].fechIda,
                    dest[38].fechVuelta, dest[38].npersona, dest[38].cod)
    update.message.reply_text(
        "Origen :" + objFly.origen + "\nDestino: " + objFly.destino + "\nAerolinea :" + objFly.aerolinea + "\nPrecio:" + str(
            objFly.precio) + "$" + "\nDuracion: " + objFly.duracion)
    update.message.reply_text(
        "A continuacion escriba /fechaida (000-00-00)\n Ejemplo /fechaida 2020-10-09 ")  # año -mes-dia
    if WRetorno == True:
        update.message.reply_text(
            "A continuacion escriba /fechavuelta (000-00-00)\n Ejemplo /fechavuelta 2020-10-09 ")  # año -mes-dia


def GPSOSL(update, context):
    global objFly, WRetorno
    objFly = Vueloa(dest[39].aerolinea, dest[39].origen, dest[39].destino, dest[39].duracion, dest[39].precio, dest[39].fechIda,
                    dest[39].fechVuelta, dest[39].npersona, dest[39].cod)
    update.message.reply_text(
        "Origen :" + objFly.origen + "\nDestino: " + objFly.destino + "\nAerolinea :" + objFly.aerolinea + "\nPrecio :" + str(
            objFly.precio) + "$" + "\nDuracion: " + objFly.duracion)
    update.message.reply_text(
        "A continuacion escriba /fechaida (000-00-00)\n Ejemplo /fechaida 2020-10-09 ")  # año -mes-dia
    if WRetorno == True:
        update.message.reply_text(
            "A continuacion escriba /fechavuelta (000-00-00)\n Ejemplo /fechavuelta 2020-10-09 ")  # año -mes-dia


def IdaVuelta(update, context):
    global WRetorno
    WRetorno = True
    update.message.reply_text("Para elegir un vuelo solo de click en el comando ejemplo / GYEUIO")
    for b in dest:
        update.message.reply_text("Origen: " + b.origen + "\nDestino :" + b.destino + "\nPrecio:" + str(
            b.precio) + "$" + "\nDuracion: " + b.duracion + "\n" + b.cod)


def fIda(update, context):
    global WRetorno
    args = context.args
    f = args[0]
    objFly.fechIda = f
    if WRetorno == False:
        update.message.reply_text(
            "A continuacion escriba: /asiento (número de asientos que desea)\n -Ejemplo /asiento 4 ")


def fechaRetorno(update, context):
    args = context.args
    f = args[0]
    objFly.fechVuelta = f
    update.message.reply_text("A continuacion escriba: /asiento (número de asientos que desea)\n -Ejemplo /asiento 4 ")


def id(update, context):
    global cedula, totalP, num, objFly, NumClient
    args = context.args
    if len(args) == 0:
        update.message.reply_text("!ingrese una cedula !!  /cedula 1234567890 ")
    else:
        ident = args[0]
        if len(ident) == 10 and ident.isdigit():
            cedula = ident
            if WRetorno == False:
                update.message.reply_text("------ DATOS DE SU VIAJE --------\n")
                update.message.reply_text("___________________________________________")
                update.message.reply_text(
                    "Su viaje: " + objFly.origen + "\nDestino: " + objFly.destino + "\nDuracion: " + objFly.duracion + "\nFecha de Ida: " + objFly.fechIda + "\nPrecio :" + str(
                        objFly.precio) + "\n Numero de asientos: " + str(objFly.npersona))
            if WRetorno == True:
                pi = objFly.precio * 2
                objFly.precio = pi
                totalP = num * objFly.precio
                update.message.reply_text("------ DATOS DE SU VIAJE --------\n")
                update.message.reply_text("-----------------------------------------------------")
                update.message.reply_text(
                    "Origen :" + objFly.origen + "\nDestino:" + objFly.destino + "\nDuracion:" + objFly.duracion + "\nFecha de Ida :" + objFly.fechIda + "\nFecha de Regreso :" + objFly.fechVuelta + "\nPrecio Base :" + str(
                        objFly.precio) + "\nNumero de asientos: " + str(objFly.npersona))
                update.message.reply_text("Precio por Ida y vuelta" + str(pi) + "$")

            update.message.reply_text("Nombre: " + NumClient)
            update.message.reply_text("Número de Identificación: " + cedula)
            update.message.reply_text("El costo total de su vuelo es de: " + str(totalP) + "$")
            update.message.reply_text("\n- /regresar")

        else:
            update.message.reply_text("! ingrese cedula valida por favor !")
            update.message.reply_text("ingrese su cedula con /cedula (recuerde que debe contener 10 digitos)")
            ident(update, context, args)


def numAsiento(update, context):
    global objFly, totalP, num
    args = context.args
    if len(args) == 0:
        update.message.reply_text( "ingresa el numero de asientos a ocupar con /asiento \n - (Ejemplo /asiento 2)")
    else:
        num = int(args[0])
        objFly.npersona = num
        Costo = int(str(objFly.precio))
        totalP = Costo * num
        update.message.reply_text("-Ingrese su nombre medainte -> /Nombre \n - Ejmplo  (Patricio Ocampo)")


def Busqueda(update, context):
    global bv
    args = context.args
    if len(args) == 0:
        busqueda(update, context)
    else:
        u = args[0]
        a = u.upper()
        for h in dest:
            if a == h.origen:
                update.message.reply_text("Origen :" + h.origen + "\nDestino :" + h.destino + "\nPrecio:" + str(
                    h.precio) + "$" + "\nDuracion:" + h.duracion + "\nAerolinea:" + h.aerolinea)
                bv = True
                update.message.reply_text("\n- /regresar")
        if bv == False:
            time.sleep(1)
            update.message.reply_text("Lo sentimos no se encontro nada ....")
            busqueda(update, context)
            update.message.reply_text("\n- /regresar")


def Allfly(update, context):
    l = 0
    update.message.reply_text("-Los vuelos disponibles son:")
    for t in dest:
        l = l + 1
        update.message.reply_text("NUmero de Vuelo " + str(l)+"#")
        update.message.reply_text("Origen :" + t.origen + "\nDestino :" + t.destino + "\nPrecio:" + str(
            t.precio) + "$" + "\nTiempo de Vuelo:" + t.duracion + "\nAerolinea:" + t.aerolinea)
    update.message.reply_text("\n- /regresar")


def busqueda(update, context):
    update.message.reply_text("-Para realizar la busqueda por ciudad de Salida use -> /Busqueda(ciudad de Salida)")
    update.message.reply_text("\n -Ejemplo:  /Buscar guayaquil")


def nom(update, context):
    update.message.reply_text("--Ingrese su nombre medainte -> /Nombre \n - Ejmplo  (Patricio Ocampo)")


def Nombre(update, context):
    global NumClient
    args = context.args
    if len(args) == 0:
        update.message.reply_text("Por favor rellene el campo con su Nombre")
        nom(update, context)
    else:
        NumClient = args[0]
        update.message.reply_text("Por favor ingrese su numero de cedula mediante -> /cedula 0000000000000")


def mensaje_nocomando(update, context):
    global enEspera

    if enEspera == 1:
        enEspera = 0
        ruta = update.message.text
        subprocess.Popen(["nohup", "wget", enlace_descarga, "-P", ruta])
        update.message.reply_text(
            "Descargando en '" + ruta + "' desde el enlace " + enlace_descarga)
    else:
        update.message.reply_text(
            "El comando enviado no es el correcto, porfavor envie correctamente el comando")




def main():

    updater = Updater(TOKEN)


    dp = updater.dispatcher

    dp.add_handler(CommandHandler("start", start))
    dp.add_handler(CommandHandler("regresar", start))
    dp.add_handler(CommandHandler("asiento", numAsiento, pass_args=True))
    dp.add_handler(CommandHandler("fechaida", fIda, pass_args=True))
    dp.add_handler(CommandHandler("fechavuelta", fechaRetorno, pass_args=True))
    dp.add_handler(CommandHandler("Busqueda", busqueda, pass_args=True))
    dp.add_handler(CommandHandler("cedula", id, pass_args=True))
    dp.add_handler(CommandHandler("GYECUE", GYECUE))
    dp.add_handler(CommandHandler("GYEETR", GYEETR))
    dp.add_handler(CommandHandler("GYEUIO", GYEUIO))
    dp.add_handler(CommandHandler("GYEGPS", GYEGPS))
    dp.add_handler(CommandHandler("GYESNC", GYESNC))
    dp.add_handler(CommandHandler("UIOMEX", UIOMEX))
    dp.add_handler(CommandHandler("GYECOR", GYECOR))
    dp.add_handler(CommandHandler("GYEBR", GYEBR))
    dp.add_handler(CommandHandler("GYEMX", GYEMX))
    dp.add_handler(CommandHandler("UIOCO", UIOCO))
    dp.add_handler(CommandHandler("UIOMX", UIOMX))
    dp.add_handler(CommandHandler("UIOMIA", UIOMIA))
    dp.add_handler(CommandHandler("UIORU", ETRNYC))
    dp.add_handler(CommandHandler("UIOMUC", UIOMAD))
    dp.add_handler(CommandHandler("CUEBR", CUEBR))
    dp.add_handler(CommandHandler("CUELAP", CUELAP))
    dp.add_handler(CommandHandler("CUEMX", CUEMX))
    dp.add_handler(CommandHandler("CUEHAV", CUEHAV))
    dp.add_handler(CommandHandler("CUEUIO", CUEUIO))
    dp.add_handler(CommandHandler("GYEDFW", GYEDFW))
    dp.add_handler(CommandHandler("UIOSVO", UIOSVO))
    dp.add_handler(CommandHandler("UIOASU", UIOASU))
    dp.add_handler(CommandHandler("GPSSCL", GPSSCL))
    dp.add_handler(CommandHandler("ETRPTY", ETRPTY))
    dp.add_handler(CommandHandler("SNCGYE", SNCGYE))
    dp.add_handler(CommandHandler("SNCCUE", SNCCUE))
    dp.add_handler(CommandHandler("CUEETR", CUEETR))
    dp.add_handler(CommandHandler("GPSLAP", GPSLAP))
    dp.add_handler(CommandHandler("GYEMRS", GYEMRS))
    dp.add_handler(CommandHandler("UIOLIS", UIOLIS))
    dp.add_handler(CommandHandler("GYECN", GYECN))
    dp.add_handler(CommandHandler("CUECN", CUECN))
    dp.add_handler(CommandHandler("ETRBAQ", ETRBAQ))
    dp.add_handler(CommandHandler("ETRMEC", ETRMEC))
    dp.add_handler(CommandHandler("GYEJP", GYEJP))
    dp.add_handler(CommandHandler("OUIMVD", OUIMVD))
    dp.add_handler(CommandHandler("CUEALC", CUEALC))
    dp.add_handler(CommandHandler("ETRBHI", ETRBHI))
    dp.add_handler(CommandHandler("GYEDUB", GYEDUB))
    dp.add_handler(CommandHandler("GPSOSL", GPSOSL))
    dp.add_handler(CommandHandler("Allfly", Allfly))
    dp.add_handler(CommandHandler("Ida", Ida))
    dp.add_handler(CommandHandler("IdayVuelta", IdaVuelta))
    
    dp.add_handler(CommandHandler("Nombre", Nombre, pass_args=True))
    dp.add_handler(CommandHandler("Buscar", Busqueda, pass_args=True))
    dp.add_handler(MessageHandler(Filters.text, mensaje_nocomando))

    updater.start_polling()
    updater.idle()


if __name__ == '__main__':
    main()
